version: 2
jobs:
  test_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install roboter-cli
      - run: npm install
      - run: npx bot

  test_node_9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install roboter-cli
      - run: npm install
      - run: npx bot

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_8
      - test_node_9
      - release:
          requires:
            - test_node_8
            - test_node_9
